CREATE SCHEMA IF NOT EXISTS efscode;
w
CREATE TABLE IF NOT EXISTS efscode.users
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

