from enum import StrEnum


class ReportsMonthlyEnum(StrEnum):
    MONTHLY_CONSUMPTION = "MONTHLY_CONSUMPTION"
    MONTHLY_DISTANCE = "MONTHLY_DISTANCE"
    MONTHLY_WORKING_TIME = "MONTHLY_WORKING_TIME"
    MONTHLY_NUMBER_OF_TRIPS = "MONTHLY_NUMBER_OF_TRIPS"
    MONTHLY_VALUE_RECEIVED = "MONTHLY_VALUE_RECEIVED"
