from enum import StrEnum


class ReportsYearlyEnum(StrEnum):
    COMSUPTION_PER_YEAR = "COMSUPTION_PER_YEAR"
    DISTANCE_PER_YEAR = "DISTANCE_PER_YEAR"
    WORKING_TIME_PER_YEAR = "WORKING_TIME_PER_YEAR"
    NUMBER_OF_TRIPS_PER_YEAR = "NUMBER_OF_TRIPS_PER_YEAR"
    VALUE_RECEIVED_PER_YEAR = "VALUE_RECEIVED_PER_YEAR"
