from enum import StrEnum


class ReportsYearlyEnum(StrEnum):
    YEARLY_CONSUMPTION = "YEARLY_CONSUMPTION"
    YEARLY_DISTANCE = "YEARLY_DISTANCE"
    YEARLY_WORKING_TIME = "YEARLY_WORKING_TIME"
    YEARLY_NUMBER_OF_TRIPS = "YEARLY_NUMBER_OF_TRIPS"
    YEARLY_VALUE_RECEIVED = "YEARLY_VALUE_RECEIVED"
