from enum import StrEnum


class ReportsWeeklyEnum(StrEnum):
    WEEKLY_CONSUMPTION = "WEEKLY_CONSUMPTION"
    WEEKLY_DISTANCE = "WEEKLY_DISTANCE"
    WEEKLY_WORKING_TIME = "WEEKLY_WORKING_TIME"
    WEEKLY_NUMBER_OF_TRIPS = "WEEKLY_NUMBER_OF_TRIPS"
    WEEKLY_VALUE_RECEIVED = "WEEKLY_VALUE_RECEIVED"
