from enum import StrEnum


class ReportsWeeklyEnum(StrEnum):
    COMSUPTION_PER_WEEK = "COMSUPTION_PER_WEEK"
    DISTANCE_PER_WEEK = "DISTANCE_PER_WEEK"
    WORKING_TIME_PER_WEEK = "WORKING_TIME_PER_WEEK"
    NUMBER_OF_TRIPS_PER_WEEK = "NUMBER_OF_TRIPS_PER_WEEK"
    VALUE_RECEIVED_PER_WEEK = "VALUE_RECEIVED_PER_WEEK"
