from enum import StrEnum


class ReportsTotalEnum(StrEnum):
    TOTAL_COMSUPTION = "TOTAL_COMSUPTION"
    TOTAL_DISTANCE = "TOTAL_DISTANCE"
    TOTAL_WORKING_TIME = "TOTAL_WORKING_TIME"
    TOTAL_NUMBER_OF_TRIPS = "TOTAL_NUMBER_OF_TRIPS"
    TOTAL_VALUE_RECEIVED = "TOTAL_VALUE_RECEIVED"
