from enum import StrEnum


class ReportsDailyEnum(StrEnum):
    DAILY_CONSUMPTION = "DAILY_CONSUMPTION"
    DAILY_DISTANCE = "DAILY_DISTANCE"
    DAILY_WORKING_TIME = "DAILY_WORKING_TIME"
    DAILY_NUMBER_OF_TRIPS = "DAILY_NUMBER_OF_TRIPS"
    DAILY_VALUE_RECEIVED = "DAILY_VALUE_RECEIVED"
