from enum import StrEnum


class ReportsMeanEnum(StrEnum):
    MEAN_DISTANCE = "MEAN_DISTANCE"
    MEAN_NUMBER_OF_TRIPS = "MEAN_NUMBER_OF_TRIPS"

    MEAN_WORKING_TIME = "MEAN_WORKING_TIME"
    MEAN_WORKING_TIME_PER_TRIP = "MEAN_WORKING_TIME_PER_TRIP"

    MEAN_CONSUMPTION_PER_TRIP = "MEAN_CONSUMPTION_PER_TRIP"
    MEAN_CONSUMPTION_PER_DISTANCE = "MEAN_CONSUMPTION_PER_DISTANCE"
    MEAN_CONSUMPTION_PER_WORKING_HOUR = "MEAN_CONSUMPTION_PER_WORKING_HOUR"
    MEAN_CONSUMPTION_PER_WORKING_MINUTE = "MEAN_CONSUMPTION_PER_WORKING_MINUTE"

    MEAN_VALUE_RECEIVED = "MEAN_VALUE_RECEIVED"
    MEAN_VALUE_RECEIVED_PER_TRIP = "MEAN_VALUE_RECEIVED_PER_TRIP"
    MEAN_VALUE_RECEIVED_PER_CONSUMPTION = "MEAN_VALUE_RECEIVED_PER_CONSUMPTION"
    MEAN_VALUE_RECEIVED_PER_WORKING_HOUR = "MEAN_VALUE_RECEIVED_PER_WORKING_HOUR"
    MEAN_VALUE_RECEIVED_PER_WORKING_MINUTE = "MEAN_VALUE_RECEIVED_PER_WORKING_MINUTE"
    MEAN_VALUE_RECEIVED_PER_DISTANCE = "MEAN_VALUE_RECEIVED_PER_DISTANCE"
