from enum import StrEnum


class ReportsEnum(StrEnum):
    ### Distance reports ###
    MEAN_DISTANCE = "MEAN_DISTANCE"
    MEAN_DISTANCE_PER_TRIP = "MEAN_DISTANCE_PER_TRIP"
    MEAN_DISTANCE_PER_WORKING_HOUR = "MEAN_DISTANCE_PER_WORKING_HOUR"
    MEAN_DISTANCE_PER_WORKING_MINUTE = "MEAN_DISTANCE_PER_WORKING_MINUTE"
    TOTAL_DISTANCE = "TOTAL_DISTANCE"

    ### Working time reports ###
    MEAN_WORKING_TIME = "MEAN_WORKING_TIME"
    MEAN_WORKING_TIME_PER_TRIP = "MEAN_WORKING_TIME_PER_TRIP"
    MEAN_WORKING_TIME_PER_DISTANCE = "MEAN_WORKING_TIME_PER_DISTANCE"
    TOTAL_WORKING_TIME = "TOTAL_WORKING_TIME"

    ### Consumption reports ###
    MEAN_CONSUMPTION_PER_DISTANCE = "MEAN_CONSUMPTION_PER_DISTANCE"
    MEAN_CONSUMPTION_PER_TRIP = "MEAN_CONSUMPTION_PER_TRIP"
    MEAN_CONSUMPTION_PER_WORKING_HOUR = "MEAN_CONSUMPTION_PER_WORKING_HOUR"
    MEAN_CONSUMPTION_PER_WORKING_MINUTE = "MEAN_CONSUMPTION_PER_WORKING_MINUTE"
    TOTAL_CONSUMPTION = "TOTAL_CONSUMPTION"
    TOTAL_CONSUMPTION_PER_TRIP = "TOTAL_CONSUMPTION_PER_TRIP"

    ### Value reports ###
    MEAN_VALUE_RECEIVED = "MEAN_VALUE_RECEIVED"
    MEAN_VALUE_RECEIVED_PER_CONSUMPTION = "MEAN_VALUE_RECEIVED_PER_CONSUMPTION"
    MEAN_VALUE_RECEIVED_PER_DISTANCE = "MEAN_VALUE_RECEIVED_PER_DISTANCE"
    MEAN_VALUE_RECEIVED_PER_WORKING_HOUR = "MEAN_VALUE_RECEIVED_PER_WORKING_HOUR"
    MEAN_VALUE_RECEIVED_PER_WORKING_MINUTE = "MEAN_VALUE_RECEIVED_PER_WORKING_MINUTE"
    MEAN_VALUE_RECEIVED_PER_TRIP = "MEAN_VALUE_RECEIVED_PER_TRIP"
    TOTAL_VALUE_RECEIVED = "TOTAL_VALUE_RECEIVED"

    ### Number of trips reports ###
    MEAN_NUMBER_OF_TRIPS = "MEAN_NUMBER_OF_TRIPS"
    MEAN_NUMBER_OF_TRIPS_PER_WORKING_HOUR = "MEAN_NUMBER_OF_TRIPS_PER_WORKING_HOUR"
    MEAN_NUMBER_OF_TRIPS_PER_WORKING_MINUTE = "MEAN_NUMBER_OF_TRIPS_PER_WORKING_MINUTE"
    MEAN_NUMBER_OF_TRIPS_PER_10_KM = "MEAN_NUMBER_OF_TRIPS_PER_10_KM"
    TOTAL_NUMBER_OF_TRIPS = "TOTAL_NUMBER_OF_TRIPS"
