from enum import StrEnum


class ReportsMonthlyEnum(StrEnum):
    COMSUPTION_PER_MONTH = "COMSUPTION_PER_MONTH"
    DISTANCE_PER_MONTH = "DISTANCE_PER_MONTH"
    WORKING_TIME_PER_MONTH = "WORKING_TIME_PER_MONTH"
    NUMBER_OF_TRIPS_PER_MONTH = "NUMBER_OF_TRIPS_PER_MONTH"
    VALUE_RECEIVED_PER_MONTH = "VALUE_RECEIVED_PER_MONTH"
