version: "3"

volumes:
  motorizen_keycloak_volume:
    name: motorizen_keycloak_volume
  motorizen_keycloak_conf_volume:
    name: motorizen_keycloak_conf_volume
  motorizen_postgres_volume:
    name: motorizen_postgres_volume
  motorizen_redis_volume:
    name: motorizen_redis_volume

networks:
  motorizen_keycloak_network:
    driver: bridge
    name: motorizen_keycloak_network
  motorizen_postgres_network:
    driver: bridge
    name: motorizen_postgres_network
  motorizen_redis_network:
    driver: bridge
    name: motorizen_redis_network

services:
  postgres:
    container_name: motorizen_postgres
    build: db_config/db.dockerfile
    image: motorizen:db
    env_file:
      - db_config/db.env
    volumes:
      - motorizen_postgres_volume:/var/lib/postgresql/data
    hostname: motorizen_postgres_volume
    networks:
      - motorizen_postgres_network
    ports:
      - "5432:5432"
    shm_size: 128mb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: motorizen_redis
    build: redis_config/redis.dockerfile
    image: motorizen:redis
    env_file:
      - redis_config/redis.env
    volumes:
      - motorizen_redis_volume:/data
    hostname: motorizen_redis
    networks:
      - motorizen_redis_network
    ports:
      - "6379:6379"
    shm_size: 128mb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3

  keycloak:
    container_name: motorizen_keycloak
    build: keycloak_config/keycloak.dockerfile
    image: motorizen:keycloak
    env_file:
      - keycloak_config/keycloak.env
    command: ["start-dev"]
    volumes:
      - motorizen_keycloak_volume:/opt/keycloak/data
      - motorizen_keycloak_conf_volume:/opt/keycloak/conf
    hostname: motorizen_keycloak
    networks:
      - motorizen_keycloak_network
      - motorizen_postgres_network
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    shm_size: 256mb
    restart: unless-stopped
    depends_on:
      postgres:
        required: true
        condition: service_healthy

  motorizen_api:
    container_name: motorizen_api
    build: api_config/api.dockerfile
    image: motorizen:api
    env_file:
      - api_config/api.env
    hostname: motorizen_api
    networks:
      - motorizen_keycloak_network
      - motorizen_postgres_network
      - motorizen_redis_network
    ports:
      - "8000:8000"
    depends_on:
      keycloak:
        condition: service_started
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    shm_size: 256mb
    restart: unless-stopped
