version: "3"

volumes:
  keycloak_data:
    name: keycloak_data
  keycloak_conf:
    name: keycloak_conf
  motorizen_db:
    name: motorizen_db
  redis_data:
    name: redis_data

networks:
  keycloak_network:
    driver: bridge
  postgres_network:
    driver: bridge
  redis_network:
    driver: bridge

services:
  keycloak:
    container_name: motorizen_keycloak
    build: keycloak_config/keycloak.dockerfile
    image: motorizen:keycloak
    env_file:
      - keycloak_config/keycloak.env
    command: ["start-dev"]
    volumes:
      - keycloak_data:/opt/keycloak/data
      - keycloak_conf:/opt/keycloak/conf
    hostname: motorizen_keycloak
    networks:
      - keycloak_network
    ports:
      - "8080:8080"
    shm_size: 256mb
    restart: unless-stopped

  postgres:
    container_name: motorizen_db
    build: db_config/db.dockerfile
    image: motorizen:db
    env_file:
      - db_config/db.env
    volumes:
      - motorizen_db:/var/lib/postgresql/data
    hostname: motorizen_db
    networks:
      - postgres_network
    ports:
      - "5432:5432"
    shm_size: 128mb
    restart: unless-stopped

  redis:
    container_name: motorizen_redis
    build: redis_config/redis.dockerfile
    image: motorizen:redis
    env_file:
      - redis_config/redis.env
    volumes:
      - redis_data:/data
    hostname: motorizen_redis
    networks:
      - redis_network
    ports:
      - "6379:6379"
    shm_size: 128mb
    restart: unless-stopped

  motorizen_api:
    container_name: motorizen_api
    build: api_config/api.dockerfile
    image: motorizen:api
    env_file:
      - api_config/api.env
    hostname: motorizen_api
    networks:
      - keycloak_network
      - postgres_network
      - redis_network
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
      - postgres
      - redis
    shm_size: 256mb
    restart: unless-stopped
