#!/bin/bash

: "${MOTORIZEN_USER:?MOTORIZEN_USER não definido}"
: "${MOTORIZEN_PASS:?MOTORIZEN_PASS não definido}"
: "${KC_DB_USER:?KC_DB_USER não definido}"
: "${KC_DB_PASS:?KC_DB_PASS não definido}"

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
DO
\$BODY\$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE rolname = '$MOTORIZEN_USER') THEN

      CREATE ROLE $MOTORIZEN_USER WITH LOGIN PASSWORD '${MOTORIZEN_PASS}';
      ALTER ROLE $MOTORIZEN_USER CREATEDB;
      GRANT ALL PRIVILEGES ON DATABASE $MOTORIZEN_DB TO $MOTORIZEN_USER;
   END IF;

   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE rolname = '$KC_DB_USER') THEN

      CREATE ROLE $KC_DB_USER WITH LOGIN PASSWORD '${KC_DB_PASS}';
   END IF;
END
\$BODY\$;
EOSQL
