SET
    ROLE motorizen;

SET
    search_path TO motorizen_schema;

CREATE TABLE
    IF NOT EXISTS "tb_brand" (
        "id_brand" SERIAL PRIMARY KEY,
        "name" VARCHAR(50) NOT NULL UNIQUE,
        "updated_at" TIMESTAMP,
        "created_at" TIMESTAMP,
        "deleted_at" TIMESTAMP
    );

CREATE TRIGGER set_brand_timestamps BEFORE INSERT
OR
UPDATE
OR DELETE ON "tb_brand" FOR EACH ROW EXECUTE FUNCTION set_timestamp ();

INSERT INTO
    "tb_brand" ("name")
VALUES
    ('Acura'),
    ('Agrale'),
    ('Alfa Romeo'),
    ('AM Gen'),
    ('Asia Motors'),
    ('Aston Martin'),
    ('Audi'),
    ('Austin'),
    ('Autobianchi'),
    ('Bentley'),
    ('Baby'),
    ('BMW'),
    ('BRM'),
    ('Bugatti'),
    ('Buick'),
    ('Buggy'),
    ('Bugre'),
    ('BYD'),
    ('CAB Motors'),
    ('Cadillac'),
    ('CBT Jipe'),
    ('Chana'),
    ('Changan'),
    ('Chery'),
    ('Chrysler'),
    ('Citroen'),
    ('Cross Lander'),
    ('Cupra'),
    ('Dacia'),
    ('Daf'),
    ('D2D'),
    ('DFSK'),
    ('Daewoo'),
    ('Daihatsu'),
    ('Dodge'),
    ('EFFA'),
    ('Engesa'),
    ('Envemo'),
    ('Ferrari'),
    ('Fiat'),
    ('Fibravan'),
    ('Ford'),
    ('Foton'),
    ('Fyber'),
    ('Geely'),
    ('GM - Chevrolet'),
    ('Great Wall'),
    ('Gurgel'),
    ('GWM'),
    ('Haima'),
    ('Hafei'),
    ('Heitech Electric'),
    ('Honda'),
    ('Hyundai'),
    ('Isuzu'),
    ('Iveco'),
    ('JAC'),
    ('Jaguar'),
    ('Jeep'),
    ('Jinbei'),
    ('JPX'),
    ('Kia Motors'),
    ('Lada'),
    ('Lamborghini'),
    ('Land Rover'),
    ('Lexus'),
    ('Lifan'),
    ('Lobini'),
    ('Lotus'),
    ('Maclaren'),
    ('Mahindra'),
    ('Maserati'),
    ('Matra'),
    ('Mazda'),
    ('Mercedes-Benz'),
    ('Mercury'),
    ('MG'),
    ('Mini'),
    ('Mitsubishi'),
    ('Miura'),
    ('Nissan'),
    ('Peugeot'),
    ('Plymouth'),
    ('Pontiac'),
    ('Porsche'),
    ('RAM'),
    ('Rely'),
    ('Renault'),
    ('Rolls-Royce'),
    ('Rover'),
    ('Saab'),
    ('Saturn'),
    ('Seat'),
    ('Seres'),
    ('Shineray'),
    ('Skoda'),
    ('smart'),
    ('Ssangyong'),
    ('Subaru'),
    ('Suzuki'),
    ('TAC'),
    ('Toyota'),
    ('Troller'),
    ('Volvo'),
    ('VW - VolksWagen'),
    ('Wake'),
    ('Wartburg'),
    ('Walk'),
    ('Wiesmann'),
    ('Yugo'),
    ('ZAZ'),
    ('Zenvo'),
    ('Zotye'),
    ('ZX');

COMMENT ON TABLE "tb_brand" IS 'Tabela de marcas de vehiculos mapeada.';