USER_BLOCKSET ROLE motorizen;

SET
    search_path TO motorizen_backlog;

CREATE TABLE
    IF NOT EXISTS "tb_backlog_event_type" (
        "id_backlog_event_type" SERIAL PRIMARY KEY NOT NULL,
        "description" VARCHAR(50) NOT NULL UNIQUE,
        "cd_backlog_severity" INTEGER NOT NULL REFERENCES "tb_backlog_severity" ("id_backlog_severity") ON DELETE SET NULL
    );

CREATE INDEX idx_backlog_severity ON "tb_backlog_event_type" ("cd_backlog_severity");

INSERT INTO
    "tb_backlog_event_type" ("description", "cd_backlog_severity")
VALUES
    ('LOGIN_SUCCESS', 1),
    ('LOGIN_REFUSED', 2),
    ('LOGIN_PASSWORD_RESET_REQUESTED', 1),
    ('LOGIN_PASSWORD_RESET_FAILED', 2),
    ('LOGIN_SESSION_EXPIRED', 3),
    ('LOGIN_IP_BLOCKED', 3),
    ('LOGIN_ACCOUNT_LOCKED', 4),
    ('LOGIN_MAX_TRY', 3),
    ('LOGIN_TOKEN_REFRESHED', 1),
    ('LOGIN_LOGOUT', 1),
    ('LOGIN_REFUSED_CSRF_TOKEN_REFUSED', 2),
    ('SYSTEM_SIGNUP_SUCCESS', 1),
    ('SYSTEM_SIGNUP_REFUSED_EMAIL_EXISTENT', 2),
    ('SYSTEM_SIGNUP_REFUSED_PASSWORD_REJECTED', 2),
    ('SYSTEM_SIGNUP_REFUSED_CSRF_TOKEN_REFUSED', 2),
    ('SYSTEM_CSRF_TOKEN_REQUESTED', 1),
    ('SUSTEM_USER_BLOCKED', 3),
    ('USER_PERMISSION_REFUSED', 2),
    ('USER_THROTLING_BLOCK', 3),
    ('USER_MAX_CAR_EXCEDED', 2),
    ('USER_INITIAL_SYNC_REQUESTED', 1),
    ('USER_UPDATE_SYNC_REQUESTED', 1),
    ('USER_INITIAL_SYNC_RECEIVED', 1),
    ('USER_PROFILE_UPDATED', 1),
    ('USER_EMAIL_CHANGED', 3),
    ('USER_PASSWORD_CHANGED', 1),
    ('USER_ROLE_MODIFIED', 3),
    ('USER_DATA_EXPORTED', 1),
    ('USER_ACCOUNT_DELETED', 3),
    ('USER_PRIVILEGE_ESCALATION', 3),
    ('CAR_CREATED', 1),
    ('CAR_UPDATED', 1),
    ('CAR_DELETED', 1),
    ('CAR_CREATION_REFUSED_EXISTENT_LICENSE_PLATE', 2),
    ('CAR_CREATION_REFUSED_EXISTENT_RENAVAN', 2),
    ('CAR_UPDATE_REFUSED_EXISTENT_LICENSE_PLATE', 2),
    ('CAR_UPDATE_REFUSED_EXISTENT_RENAVAN', 2),
    ('CAR_NOT_FOUND', 2),
    ('CAR_DEDUPED', 1),
    ('REGISTER_CREATED', 1),
    ('REGISTER_UPDATED', 1),
    ('REGISTER_DELETED', 1),
    ('REGISTER_DEDUPED', 1),
    ('REGISTER_CREATION_REFUSED', 2),
    ('REGISTER_UPDATE_REFUSED', 2),
    ('REGISTER_BULK_IMPORT_STARTED', 1),
    ('REGISTER_BULK_IMPORT_FAILED', 2),
    ('REGISTER_DATA_CORRUPTED', 3),
    ('REGISTER_AUDIT_LOG_ACCESSED', 4),
    ('PAYMENT_PROCESSED', 1),
    ('PAYMENT_FAILED', 2),
    ('PAYMENT_REFUNDED', 2),
    ('PAYMENT_RETRY_SCHEDULED', 2),
    ('PAYMENT_FAILED', 2),
    ('SYSTEM_COMMUNICATION_ERROR_DATABASE_PROVIDER', 4),
    ('SYSTEM_COMMUNICATION_ERROR_CACHE_PROVIDER', 3),
    ('SYSTEM_COMMUNICATION_ERROR_AUTH_PROVIDER', 4),
    ('SYSTEM_MAINTENANCE_MODE_ENABLED', 3),
    ('SYSTEM_BACKUP_FAILED', 4),
    ('SYSTEM_BACKUP_COMPLETED', 1),
    ('SYSTEM_API_RATE_LIMIT_EXCEEDED', 3),
    ('SYSTEM_CONFIGURATION_CHANGED', 3),
    ('SYSTEM_HIGH_CPU_USAGE', 4),
    ('SYSTEM_MEMORY_LEAK_DETECTED', 4),
    ('SECURITY_BREACH_ATTEMPT', 4),
    ('SECURITY_INVALID_TOKEN_USED', 4),
    ('SECURITY_USER_SESSION_HIJACK_ATTEMPT', 4);

COMMENT ON TABLE "tb_backlog_event_type" IS 'Tabela de tipos de eventos de backlog';